### PR TITLE
Relax remote comparison

### PR DESCRIPTION
**Pull request by FiloSottile**

### CODE REVIEW

**Comment by shurcooL** [comment]
Hi Filippo, thanks for contributing!

Can I ask what's the problem you're trying to resolve with this PR? What's the rationale for applying this change?

I'd also like to point your attention towards the following test case in `status` package, which is [currently failing](https://travis-ci.org/shurcooL/gostatus/builds/212779068) in this PR:

```Go
{
	// .git suffix does not have special treatment, and these are not considered as equal URLs.
	// See https://github.com/shurcooL/gostatus/issues/37#issuecomment-225336823 for rationale.
	rawurl0: "https://github.com/user/repo",
	rawurl1: "https://github.com/user/repo.git",
	want:    false,
},
```

Source: https://github.com/shurcooL/gostatus/blob/97e8adbc5da9bb3524e66e04d43deb84a42b35a1/status/url_test.go#L19-L25.

The behavior you're changing in this PR is not an accidental bug, but rather a conscious design decision. As the comment points out, please https://github.com/shurcooL/gostatus/issues/37#issuecomment-225336823 for full rationale, if you haven't seen it already. What do you think of it?

**Comment by shurcooL** [comment]
@FiloSottile, did you see my question above?

**Comment by FiloSottile** [comment]
Hi Dmitri, oops, I didn't notice the previous discussion.

The motive behind the PR is simple. I took the tool, pointed it at an existing, messy GOPATH, with the task of cleaning it up, which is exactly what's it has been great for. There were some cases that required manual intervention that the tool could have safely handled automatically, so I added support for them.

I also see the simplicity argument. Were it me, I'd take the convenience tradeoff. But it's your project, and I won't be offended by the slightest if you decide to close the PR. Otherwise, let me know and I'll fix the tests.

Sorry for not doing my homework, and thanks for the tool!

**Comment by shurcooL** [comment]
Thanks for the explanation @FiloSottile.

> I took the tool, pointed it at an existing, messy GOPATH, with the task of cleaning it up, which is exactly what's it has been great for.

That's exactly what I created it for. 👍 Glad it's helpful.

> There were some cases that required manual intervention that the tool could have safely handled automatically, so I added support for them.
>
> I also see the simplicity argument. Were it me, I'd take the convenience tradeoff. But it's your project, and I won't be offended by the slightest if you decide to close the PR. Otherwise, let me know and I'll fix the tests.

Understandable.

I actually have some additional thoughts on what can be done to improve this situation.

This issue is currently in a "NeedsDecision" status. Once a decision is made, the implementation is trivial and I can do it myself. I'm already tracking the decision and having discussion at https://github.com/shurcooL/Go-Package-Store/issues/78, so I'll close this PR to centralize the discussion. I suggest you follow that issue if you're interested in updates.

I've also reported an issue with `go get -u` behavior upstream at https://github.com/golang/go/issues/20039. Since `gostatus` is meant to follow and augment `cmd/go`, it's likely I'll end up adopting whatever decision gets made upstream.

> Sorry for not doing my homework, and thanks for the tool!

No problem. Thanks for using it, and for trying to contribute!

**Comment by shurcooL** [comment]
Just as a heads up, in the meantime, you can still use `-f` flag to disable remote URL checking.

```
  -f	Force not to verify that each package has been checked out from the source
control repository implied by its import path. This can be useful if the source is
a local fork of the original.
```

**Pull request closed without merging**
